language: node_js
sudo: required
dist: trusty
node_js:
  - "node"
  - "8"
addons: 
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  directories:
  - node_modules    
  - bower_components
install: 
- npm install -g yarn
- yarn add global bower
- yarn add global polymer-cli
- node -v
- polymer --version
- yarn --version
- yarn install
- bower install
before_script:
- mkdir -p ~/bin
- ln -s /usr/bin/google-chrome-beta ~/bin/google-chrome
- export PATH=$HOME/bin:$PATH
- ls
script:
- polymer build -v
- polymer lint --input src/**/*.html
notifications:
  email: false
